# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: definition.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64\x65\x66inition.proto\"<\n\x07Officer\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x10\n\x08lastname\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\xaf\x01\n\x08ShipData\x12\x1d\n\talignment\x18\x01 \x01(\x0e\x32\n.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1e\n\nship_class\x18\x03 \x01(\x0e\x32\n.ShipClass\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x0c\n\x04size\x18\x05 \x01(\r\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x19\n\x07officer\x18\x07 \x03(\x0b\x32\x08.Officer\x12\x0e\n\x06status\x18\x08 \x01(\t\"\x18\n\x06\x63oords\x12\x0e\n\x06\x63oords\x18\x01 \x01(\t*>\n\tAlignment\x12\x10\n\x0c\x41LIGN_CENTER\x10\x00\x12\r\n\tALIGN_TOP\x10\x01\x12\x10\n\x0c\x41LIGN_BOTTOM\x10\x02*`\n\tShipClass\x12\x0c\n\x08\x43ORVETTE\x10\x00\x12\x0b\n\x07\x46RIGATE\x10\x01\x12\x0b\n\x07\x43RUISER\x10\x02\x12\r\n\tDESTROYER\x10\x03\x12\x0b\n\x07\x43\x41RRIER\x10\x04\x12\x0f\n\x0b\x44READNOUGHT\x10\x05\x32\x32\n\nRouteGuide\x12$\n\nGetFeature\x12\x07.coords\x1a\t.ShipData\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'definition_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ALIGNMENT']._serialized_start=286
  _globals['_ALIGNMENT']._serialized_end=348
  _globals['_SHIPCLASS']._serialized_start=350
  _globals['_SHIPCLASS']._serialized_end=446
  _globals['_OFFICER']._serialized_start=20
  _globals['_OFFICER']._serialized_end=80
  _globals['_SHIPDATA']._serialized_start=83
  _globals['_SHIPDATA']._serialized_end=258
  _globals['_COORDS']._serialized_start=260
  _globals['_COORDS']._serialized_end=284
  _globals['_ROUTEGUIDE']._serialized_start=448
  _globals['_ROUTEGUIDE']._serialized_end=498
# @@protoc_insertion_point(module_scope)
